// SPDX-License-Identifier: Apache-2.0
//
// Runs the Rust kernels against the same fixtures tests/unit/test_ops.c feeds the C
// ones, at the tolerances in tests/fixtures/ops/MANIFEST.json. The fixtures are
// generated by tools/emit_fixtures.py from the pure-torch reference, so this compares
// against torch, not against the C port -- a port that agrees only with itself proves
// nothing.

use std::path::PathBuf;

use k3::ops;
use serde_json::Value;

fn ops_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/fixtures/ops")
        .canonicalize()
        .expect("tests/fixtures/ops must exist")
}

fn load(name: &str) -> Value {
    let p = ops_dir().join(format!("{name}.json"));
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{p:?}: {e}")))
        .unwrap_or_else(|e| panic!("{p:?}: {e}"))
}

fn tol() -> (f32, f32) {
    let m = load("MANIFEST");
    let t = &m["tolerance"];
    (
        t["fp32_abs"].as_f64().expect("fp32_abs") as f32,
        t["fp32_rel"].as_f64().expect("fp32_rel") as f32,
    )
}

fn ten(v: &Value, key: &str) -> Vec<f32> {
    v[key]["data"]
        .as_array()
        .unwrap_or_else(|| panic!("{key} has no data array"))
        .iter()
        .map(|x| x.as_f64().unwrap_or(f64::NAN) as f32)
        .collect()
}

fn shape(v: &Value, key: &str) -> Vec<usize> {
    v[key]["shape"]
        .as_array()
        .unwrap_or_else(|| panic!("{key} has no shape"))
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect()
}

fn f(v: &Value, key: &str) -> f32 {
    v[key].as_f64().unwrap_or_else(|| panic!("{key} missing")) as f32
}

fn i(v: &Value, key: &str) -> usize {
    v[key].as_u64().unwrap_or_else(|| panic!("{key} missing")) as usize
}

#[track_caller]
fn close(what: &str, got: &[f32], want: &[f32]) {
    let (atol, rtol) = tol();
    assert_eq!(got.len(), want.len(), "{what}: length");
    let mut worst = 0f32;
    let mut worst_at = 0usize;
    for (n, (&g, &w)) in got.iter().zip(want).enumerate() {
        if g.is_nan() != w.is_nan() {
            panic!("{what}[{n}]: NaN mismatch, got {g} want {w}");
        }
        if g.is_nan() {
            continue;
        }
        let d = (g - w).abs();
        let allowed = atol + rtol * w.abs();
        if d > allowed && d / allowed > worst {
            worst = d / allowed;
            worst_at = n;
        }
    }
    if worst > 0.0 {
        let (g, w) = (got[worst_at], want[worst_at]);
        panic!(
            "{what}: worst violation at [{worst_at}]: got {g:e} want {w:e} \
             (|d| {:e} > atol {atol:e} + rtol {rtol:e} * |want|)",
            (g - w).abs()
        );
    }
}

#[test]
fn rmsnorm() {
    let v = load("rmsnorm");
    let (x, w, want) = (ten(&v, "in"), ten(&v, "weight"), ten(&v, "out"));
    let sh = shape(&v, "in");
    let (rows, n) = (sh[0], sh[1]);
    let mut got = vec![0f32; rows * n];
    for r in 0..rows {
        let (a, b) = (&x[r * n..][..n], &mut got[r * n..][..n]);
        ops::rmsnorm(b, a, &w, n, f(&v, "eps"));
    }
    close("rmsnorm", &got, &want);
}

#[test]
fn situ_glu() {
    let v = load("situ_glu");
    let (x, want) = (ten(&v, "in"), ten(&v, "out"));
    let sh = shape(&v, "in");
    let (rows, two_n) = (sh[0], sh[1]);
    let n = two_n / 2;
    let (b1, b2) = (f(&v, "beta"), f(&v, "linear_beta"));
    let mut got = vec![0f32; rows * n];
    for r in 0..rows {
        ops::situ_glu(&mut got[r * n..][..n], &x[r * two_n..][..two_n], n, b1, b2);
    }
    close("situ_glu", &got, &want);

    // The fixture also pins the bound b1*b2 = 100; a capped-gate sigmoid would still
    // satisfy it, which is why the fixture alone is not the whole guarantee.
    let max_abs = f(&v, "max_abs");
    assert!(
        got.iter().all(|g| g.abs() <= max_abs + 1e-3),
        "situ_glu exceeded the fixture's max_abs {max_abs}"
    );
}

#[test]
fn shortconv() {
    let v = load("shortconv");
    let (k, channels) = (i(&v, "kernel"), i(&v, "channels"));
    let w = ten(&v, "weight");
    // in is [1, T, channels]; derive T from the element count so a leading batch
    // dimension in the fixture cannot be mistaken for T.
    let t_len = ten(&v, "in").len() / channels;

    let mut state = vec![0f32; channels * (k - 1)];
    let mut got = vec![0f32; t_len * channels];
    ops::shortconv(
        &mut got,
        &ten(&v, "in"),
        &w,
        Some(&mut state),
        channels,
        k,
        t_len,
    );
    close("shortconv", &got, &ten(&v, "out"));
    close("shortconv state_after", &state, &ten(&v, "state_after"));

    // The carried state is the point: a second call must continue the sequence.
    let t2 = ten(&v, "in_next").len() / channels;
    let mut got2 = vec![0f32; t2 * channels];
    ops::shortconv(
        &mut got2,
        &ten(&v, "in_next"),
        &w,
        Some(&mut state),
        channels,
        k,
        t2,
    );
    close("shortconv continued", &got2, &ten(&v, "out_next"));
}

#[test]
fn kda_decay() {
    let v = load("kda_decay");
    let z = ten(&v, "z");
    let (a_log, dt_bias) = (ten(&v, "A_log"), ten(&v, "dt_bias"));
    // A_log is [H] (PER HEAD) and dt_bias is [H*D], so both sizes come from the
    // tensors themselves rather than from z's leading batch dimensions.
    let h_n = a_log.len();
    let p = dt_bias.len();
    let d_n = p / h_n;
    let rows = z.len() / p;
    let lb = f(&v, "lower_bound");

    let mut g = vec![0f32; rows * p];
    let mut alpha = vec![0f32; rows * p];
    for r in 0..rows {
        ops::kda_decay(
            &mut g[r * p..][..p],
            &mut alpha[r * p..][..p],
            &z[r * p..][..p],
            &a_log,
            &dt_bias,
            h_n,
            d_n,
            lb,
        );
    }
    close("kda_decay g", &g, &ten(&v, "g"));
    close("kda_decay alpha", &alpha, &ten(&v, "alpha"));

    // alpha lives in (e^lb, 1]; the fixture records the observed span.
    let (amin, amax) = (f(&v, "alpha_min"), f(&v, "alpha_max"));
    let got_min = alpha.iter().cloned().fold(f32::INFINITY, f32::min);
    let got_max = alpha.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    assert!((got_min - amin).abs() < 1e-5, "alpha_min {got_min} vs {amin}");
    assert!((got_max - amax).abs() < 1e-5, "alpha_max {got_max} vs {amax}");
}

#[test]
fn router() {
    let v = load("router");
    let (topk, n_experts) = (i(&v, "top_k"), i(&v, "n_experts"));
    let gate = ten(&v, "gate_weight");
    let bias = ten(&v, "bias");
    let x = ten(&v, "in");
    let sh = shape(&v, "in");
    let (rows, hidden) = (sh[0], sh[1]);

    let want_idx = ten(&v, "topk_idx");
    let want_wt = ten(&v, "topk_weight");

    let mut got_idx = vec![0f32; rows * topk];
    let mut got_wt = vec![0f32; rows * topk];
    for r in 0..rows {
        let mut idx = vec![0i32; topk];
        let mut wt = vec![0f32; topk];
        ops::router(
            &mut idx,
            &mut wt,
            &x[r * hidden..][..hidden],
            &gate,
            Some(&bias),
            hidden,
            n_experts,
            topk,
            true,
            1.0,
        );
        for j in 0..topk {
            got_idx[r * topk + j] = idx[j] as f32;
            got_wt[r * topk + j] = wt[j];
        }
    }
    // Indices must match exactly: a different expert is a different model, not a
    // rounding difference.
    assert_eq!(got_idx, want_idx, "router selected different experts");
    close("router weights", &got_wt, &want_wt);
}

#[test]
fn attnres() {
    let v = load("attnres");
    let eps = f(&v, "eps");
    let nsrc = i(&v, "n_sources");
    let prefix = ten(&v, "prefix_sum");
    let blocks = ten(&v, "block_residual");
    let norm_w = ten(&v, "norm_weight");
    let proj_w = ten(&v, "proj_weight");
    let sh = shape(&v, "prefix_sum");
    let (rows, n) = (sh[0], sh[1]);
    let nblk = shape(&v, "block_residual")[1];

    // The norm gain and the scoring projection collapse to ONE vector.
    let fold: Vec<f32> = norm_w.iter().zip(&proj_w).map(|(a, b)| a * b).collect();
    close("attnres fold", &fold, &ten(&v, "fold_hint"));

    let mut got = vec![0f32; rows * n];
    let mut src = vec![0f32; nsrc * n];
    for t in 0..rows {
        for b in 0..nsrc - 1 {
            src[b * n..][..n].copy_from_slice(&blocks[(t * nblk + b) * n..][..n]);
        }
        src[(nsrc - 1) * n..][..n].copy_from_slice(&prefix[t * n..][..n]);
        ops::attn_res(&mut got[t * n..][..n], &src, &fold, nsrc, n, eps);
    }
    close("attnres", &got, &ten(&v, "out"));
}

fn kda_recurrence(name: &str) {
    let v = load(name);
    let (t_len, h_n, dk, dv) = (i(&v, "T"), i(&v, "H"), i(&v, "d_k"), i(&v, "d_v"));
    let q_scale = f(&v, "q_scale");
    let (q, k, vv, alpha, beta) = (
        ten(&v, "q"),
        ten(&v, "k"),
        ten(&v, "v"),
        ten(&v, "alpha"),
        ten(&v, "beta"),
    );
    let p = h_n * dk;

    let mut state = vec![0f32; h_n * dk * dv];
    let mut out = vec![0f32; t_len * p];
    // Heads are independent and each walks its own t in order; the recurrence is
    // sequential in t WITHIN a head.
    for h in 0..h_n {
        let mut scaled = vec![0f32; dk];
        for t in 0..t_len {
            let off = t * p + h * dk;
            for d in 0..dk {
                scaled[d] = q[off + d] * q_scale;
            }
            let (s_lo, s_hi) = (h * dk * dv, (h + 1) * dk * dv);
            let mut o = vec![0f32; dv];
            ops::kda_step(
                &mut state[s_lo..s_hi],
                &mut o,
                &scaled,
                &k[off..off + dk],
                &vv[off..off + dv],
                &alpha[off..off + dk],
                beta[t * h_n + h],
                dk,
                dv,
            );
            out[off..off + dv].copy_from_slice(&o);
        }
    }
    close(&format!("{name} out"), &out, &ten(&v, "out"));
    close(&format!("{name} state_out"), &state, &ten(&v, "state_out"));
}

#[test]
fn kda_recur_single_token() {
    kda_recurrence("kda_recur1");
}

#[test]
fn kda_recur_eight_tokens() {
    kda_recurrence("kda_recur8");
}

fn mla_weights(v: &Value) -> (k3::ops::MlaDims, Vec<Vec<f32>>) {
    let d = k3::ops::MlaDims {
        hidden: shape(v, "in")[2],
        n_heads: i(v, "n_heads"),
        qk_nope: i(v, "qk_nope"),
        qk_rope: i(v, "qk_rope"),
        v_head: i(v, "v_head"),
        q_lora: i(v, "q_lora"),
        kv_lora: i(v, "kv_lora"),
        rms_eps: f(v, "rms_eps"),
    };
    let t = vec![
        ten(v, "q_a_proj_weight"),
        ten(v, "q_b_proj_weight"),
        ten(v, "kv_a_proj_with_mqa_weight"),
        ten(v, "kv_b_proj_weight"),
        ten(v, "o_proj_weight"),
        ten(v, "g_proj_weight"),
        ten(v, "q_a_layernorm_weight"),
        ten(v, "kv_a_layernorm_weight"),
    ];
    (d, t)
}

fn mla_w(t: &[Vec<f32>]) -> k3::ops::MlaW<'_> {
    k3::ops::MlaW {
        q_a: k3::ops::W::F32(&t[0]),
        q_b: k3::ops::W::F32(&t[1]),
        kv_a: k3::ops::W::F32(&t[2]),
        kv_b: k3::ops::W::F32(&t[3]),
        o: k3::ops::W::F32(&t[4]),
        g: Some(k3::ops::W::F32(&t[5])),
        q_a_norm: &t[6],
        kv_a_norm: &t[7],
    }
}

#[test]
fn mla() {
    let v = load("mla");
    let (d, t) = mla_weights(&v);
    let w = mla_w(&t);
    let x = ten(&v, "in");
    let t_len = x.len() / d.hidden;
    let mut got = vec![0f32; t_len * d.hidden];
    k3::ops::mla_cached(&mut got, &x, &w, &d, t_len, None, 0);
    close("mla", &got, &ten(&v, "out"));
}

// The cached path must agree with the self-contained sweep: feeding tokens one at a
// time with a KV cache is what makes incremental decode possible, and a divergence here
// is prefill and decode producing different text from the same prompt.
#[test]
fn mla_incremental_matches_the_uncached_sweep() {
    let v = load("mla");
    let (d, t) = mla_weights(&v);
    let w = mla_w(&t);
    let x = ten(&v, "in");
    let e = d.hidden;
    let t_len = x.len() / e;
    let kvd = d.qk_nope + d.v_head;

    let mut kvc = vec![0f32; t_len * d.n_heads * kvd];
    let mut ropec = vec![0f32; t_len * d.qk_rope];
    let mut got = vec![0f32; t_len * e];
    for step in 0..t_len {
        k3::ops::mla_cached(
            &mut got[step * e..][..e],
            &x[step * e..][..e],
            &w,
            &d,
            1,
            Some((&mut kvc, &mut ropec)),
            step,
        );
    }
    close("mla incremental", &got, &ten(&v, "out"));
}

#[test]
fn moe() {
    let v = load("moe");
    let d = k3::ops::MoeDims {
        hidden: i(&v, "hidden"),
        latent: i(&v, "latent"),
        moe_inter: i(&v, "moe_inter"),
        n_experts: i(&v, "n_experts"),
        topk: i(&v, "top_k"),
        n_shared: i(&v, "n_shared"),
        routed_scale: f(&v, "routed_scale"),
        renorm: i(&v, "renorm") != 0,
        latent_norm: i(&v, "latent_norm") != 0,
        rms_eps: f(&v, "rms_eps"),
        situ_b1: f(&v, "situ_b1"),
        situ_b2: f(&v, "situ_b2"),
    };
    let (mut w1, mut w3, mut w2) = (Vec::new(), Vec::new(), Vec::new());
    for e in 0..d.n_experts {
        w1.extend(ten(&v, &format!("experts_{e}_w1_weight")));
        w3.extend(ten(&v, &format!("experts_{e}_w3_weight")));
        w2.extend(ten(&v, &format!("experts_{e}_w2_weight")));
    }
    let gate = ten(&v, "gate_weight");
    let bias = ten(&v, "e_score_correction_bias");
    let (down, up) = (ten(&v, "down_weight"), ten(&v, "up_weight"));
    let norm = ten(&v, "norm_weight");
    let (s1, s3, s2) = (
        ten(&v, "shared_w1_weight"),
        ten(&v, "shared_w3_weight"),
        ten(&v, "shared_w2_weight"),
    );
    let w = k3::ops::MoeW {
        gate: &gate,
        bias: Some(&bias),
        w1: &w1,
        w3: &w3,
        w2: &w2,
        latent_norm: &norm,
        down: k3::ops::W::F32(&down),
        up: k3::ops::W::F32(&up),
        sh1: k3::ops::W::F32(&s1),
        sh3: k3::ops::W::F32(&s3),
        sh2: k3::ops::W::F32(&s2),
    };
    let x = ten(&v, "in");
    let t_len = x.len() / d.hidden;
    let mut got = vec![0f32; t_len * d.hidden];
    k3::ops::moe(&mut got, &x, &w, &d, t_len);
    close("moe", &got, &ten(&v, "out"));
}

fn kda_layer_case(name: &str) {
    let v = load(name);
    let d = k3::ops::KdaDims {
        hidden: shape(&v, "in")[2],
        heads: i(&v, "H"),
        head_dim: i(&v, "d_k"),
        conv_k: i(&v, "conv_k"),
        gate_lb: f(&v, "lower_bound"),
        rms_eps: f(&v, "rms_eps"),
    };
    let t: Vec<Vec<f32>> = [
        "q_proj", "k_proj", "v_proj", "g_proj", "o_proj", "f_a", "f_b", "b_proj", "q_conv",
        "k_conv", "v_conv", "A_log", "dt_bias", "o_norm",
    ]
    .iter()
    .map(|k| ten(&v, k))
    .collect();
    let w = k3::ops::KdaW {
        q: k3::ops::W::F32(&t[0]),
        k: k3::ops::W::F32(&t[1]),
        v: k3::ops::W::F32(&t[2]),
        g: k3::ops::W::F32(&t[3]),
        o: k3::ops::W::F32(&t[4]),
        f_a: k3::ops::W::F32(&t[5]),
        f_b: k3::ops::W::F32(&t[6]),
        b: k3::ops::W::F32(&t[7]),
        q_conv: &t[8],
        k_conv: &t[9],
        v_conv: &t[10],
        a_log: &t[11],
        dt_bias: &t[12],
        o_norm: &t[13],
    };
    let x = ten(&v, "in");
    let t_len = x.len() / d.hidden;
    let mut state = vec![0f32; k3::ops::kda_state_len(&d)];
    let mut got = vec![0f32; t_len * d.hidden];
    k3::ops::kda_layer(&mut got, &x, &w, &d, t_len, &mut state);
    close(&format!("{name} out"), &got, &ten(&v, "out"));
    // The recurrent block is the head of the state; the ShortConv history follows it.
    let rec = d.heads * d.head_dim * d.head_dim;
    close(&format!("{name} state_out"), &state[..rec], &ten(&v, "state_out"));
}

#[test]
fn kda_layer_single_token() {
    kda_layer_case("kda_layer1");
}

#[test]
fn kda_layer_eight_tokens() {
    kda_layer_case("kda_layer8");
}

// A whole decoder layer: the AttnRes wiring plus attention plus the MoE. What this
// exercises that nothing else does is the aggregate REPLACING the layer input, the
// snapshot push, and the prefix_sum reset at a block boundary. layer_kda is index 1
// (not a boundary, so the running residual survives); layer_mla is index 3, which IS
// one at block size 3. Between them both paths run.
//
// Like tests/unit/test_ops.c, this gates `out` only: block_residual_out is
// informational in the fixture and the C harness does not check it either.
fn layer_case(name: &str) {
    let v = load(name);
    let cfg = load("MANIFEST");
    let c = &cfg["config"];
    let hidden = i(&v, "hidden");
    let rms_eps = f(&v, "rms_eps");
    let layer_idx = i(&v, "layer_idx");
    let block = i(&v, "attn_res_block_size");
    let n_layers = c["num_hidden_layers"].as_u64().unwrap() as usize;
    let maxb = n_layers / block + 2;

    let din = shape(&v, "in");
    let t_len = din[1];
    let nb_in = shape(&v, "block_residual_in")[1];

    let p = |k: &str| ten(&v, k);
    let (in_norm, post_norm) = (p("input_layernorm_weight"), p("post_attention_layernorm_weight"));
    let (arn, arp) = (p("self_attention_res_norm_weight"), p("self_attention_res_proj_weight"));
    let (mrn, mrp) = (p("mlp_res_norm_weight"), p("mlp_res_proj_weight"));

    let d = k3::ops::MoeDims {
        hidden,
        latent: c["routed_expert_hidden_size"].as_u64().unwrap() as usize,
        moe_inter: c["moe_intermediate_size"].as_u64().unwrap() as usize,
        n_experts: c["num_experts"].as_u64().unwrap() as usize,
        topk: c["num_experts_per_token"].as_u64().unwrap() as usize,
        n_shared: c["num_shared_experts"].as_u64().unwrap() as usize,
        routed_scale: c["routed_scaling_factor"].as_f64().unwrap() as f32,
        renorm: c["moe_renormalize"].as_bool().unwrap_or(true),
        latent_norm: c["latent_moe_use_norm"].as_bool().unwrap_or(true),
        rms_eps,
        situ_b1: c["situ_beta"].as_f64().unwrap() as f32,
        situ_b2: c["situ_linear_beta"].as_f64().unwrap() as f32,
    };
    let (mut w1, mut w3, mut w2) = (Vec::new(), Vec::new(), Vec::new());
    for e in 0..d.n_experts {
        w1.extend(p(&format!("mlp_experts_{e}_w1_weight")));
        w3.extend(p(&format!("mlp_experts_{e}_w3_weight")));
        w2.extend(p(&format!("mlp_experts_{e}_w2_weight")));
    }
    let mt: Vec<Vec<f32>> = [
        "mlp_gate_weight", "mlp_e_score_correction_bias", "mlp_down_weight", "mlp_up_weight",
        "mlp_norm_weight", "mlp_shared_w1_weight", "mlp_shared_w3_weight", "mlp_shared_w2_weight",
    ]
    .iter()
    .map(|k| p(k))
    .collect();
    let mw = k3::ops::MoeW {
        gate: &mt[0],
        bias: Some(&mt[1]),
        w1: &w1,
        w3: &w3,
        w2: &w2,
        latent_norm: &mt[4],
        down: k3::ops::W::F32(&mt[2]),
        up: k3::ops::W::F32(&mt[3]),
        sh1: k3::ops::W::F32(&mt[5]),
        sh3: k3::ops::W::F32(&mt[6]),
        sh2: k3::ops::W::F32(&mt[7]),
    };

    let kd = k3::ops::KdaDims {
        hidden,
        heads: c["kda_num_heads"].as_u64().unwrap() as usize,
        head_dim: c["kda_head_dim"].as_u64().unwrap() as usize,
        conv_k: c["short_conv_kernel_size"].as_u64().unwrap() as usize,
        gate_lb: c["gate_lower_bound"].as_f64().unwrap() as f32,
        rms_eps,
    };
    let md = k3::ops::MlaDims {
        hidden,
        n_heads: c["num_attention_heads"].as_u64().unwrap() as usize,
        qk_nope: c["qk_nope_head_dim"].as_u64().unwrap() as usize,
        qk_rope: c["qk_rope_head_dim"].as_u64().unwrap() as usize,
        v_head: c["v_head_dim"].as_u64().unwrap() as usize,
        q_lora: c["q_lora_rank"].as_u64().unwrap() as usize,
        kv_lora: c["kv_lora_rank"].as_u64().unwrap() as usize,
        rms_eps,
    };

    let is_mla = v["is_mla"].as_bool().unwrap_or(false);
    let kt: Vec<Vec<f32>> = if is_mla {
        Vec::new()
    } else {
        [
            "self_attn_q_proj_weight", "self_attn_k_proj_weight", "self_attn_v_proj_weight",
            "self_attn_g_proj_weight", "self_attn_o_proj_weight", "self_attn_f_a_proj_weight",
            "self_attn_f_b_proj_weight", "self_attn_b_proj_weight", "self_attn_q_conv1d_weight",
            "self_attn_k_conv1d_weight", "self_attn_v_conv1d_weight", "self_attn_A_log",
            "self_attn_dt_bias", "self_attn_o_norm_weight",
        ]
        .iter()
        .map(|k| p(k))
        .collect()
    };
    let at: Vec<Vec<f32>> = if is_mla {
        [
            "self_attn_q_a_proj_weight", "self_attn_q_b_proj_weight",
            "self_attn_kv_a_proj_with_mqa_weight", "self_attn_kv_b_proj_weight",
            "self_attn_o_proj_weight", "self_attn_g_proj_weight",
            "self_attn_q_a_layernorm_weight", "self_attn_kv_a_layernorm_weight",
        ]
        .iter()
        .map(|k| p(k))
        .collect()
    } else {
        Vec::new()
    };

    let kw;
    let aw;
    let attn = if is_mla {
        aw = k3::ops::MlaW {
            q_a: k3::ops::W::F32(&at[0]),
            q_b: k3::ops::W::F32(&at[1]),
            kv_a: k3::ops::W::F32(&at[2]),
            kv_b: k3::ops::W::F32(&at[3]),
            o: k3::ops::W::F32(&at[4]),
            g: Some(k3::ops::W::F32(&at[5])),
            q_a_norm: &at[6],
            kv_a_norm: &at[7],
        };
        k3::ops::Attn::Mla(&aw, &md)
    } else {
        kw = k3::ops::KdaW {
            q: k3::ops::W::F32(&kt[0]),
            k: k3::ops::W::F32(&kt[1]),
            v: k3::ops::W::F32(&kt[2]),
            g: k3::ops::W::F32(&kt[3]),
            o: k3::ops::W::F32(&kt[4]),
            f_a: k3::ops::W::F32(&kt[5]),
            f_b: k3::ops::W::F32(&kt[6]),
            b: k3::ops::W::F32(&kt[7]),
            q_conv: &kt[8],
            k_conv: &kt[9],
            v_conv: &kt[10],
            a_log: &kt[11],
            dt_bias: &kt[12],
            o_norm: &kt[13],
        };
        k3::ops::Attn::Kda(&kw, &kd)
    };

    let lw = k3::ops::LayerW {
        in_norm: &in_norm,
        post_norm: &post_norm,
        attn_res_norm: &arn,
        attn_res_proj: &arp,
        mlp_res_norm: &mrn,
        mlp_res_proj: &mrp,
        attn,
        mlp: k3::ops::Mlp::Moe(&mw, &d),
    };

    let fold_a = k3::ops::fold_residual(&arn, &arp);
    let fold_m = k3::ops::fold_residual(&mrn, &mrp);

    let h0 = ten(&v, "in");
    let mut res = k3::ops::AttnResidual::new(&h0, t_len, hidden, maxb, rms_eps);
    res.seed_blocks(&ten(&v, "block_residual_in"), nb_in);
    res.begin_layer(layer_idx, block, &fold_a, &fold_m);

    let mut state = vec![0f32; k3::ops::kda_state_len(&kd)];
    k3::ops::decoder_layer(&mut res, &lw, hidden, t_len, &mut state, rms_eps);

    use k3::ops::Residual;
    close(name, res.hidden(), &ten(&v, "out"));

    let boundary = layer_idx % block == 0;
    assert_eq!(res.n_blocks(), nb_in + usize::from(boundary), "{name}: block count transition");
}

#[test]
fn layer_kda() {
    layer_case("layer_kda");
}

#[test]
fn layer_mla() {
    layer_case("layer_mla");
}

// ---------------------------------------------------- KDA under 1 vs N threads --------
//
// The recurrence is parallelised over heads (k3_ops.c:869-873, mirrored in ops::kda_layer)
// and the C claims the result is bit-identical to the serial form, "gated by test_ops'
// kda fixtures under 1 vs N threads". The fixture above gates against the torch reference
// inside a tolerance; this gates the two thread counts against EACH OTHER, bitwise.
//
// The distinction matters here more than in the matmuls. Each head carries its own
// recurrent state across the sequence, so a head that read a neighbour's state, or a
// scatter that mixed two heads' outputs, would still produce a bounded, plausible,
// evolving stream -- the failure mode this codebase exists to catch. Both `out` and the
// recurrent state are compared, because a wrong state is invisible in one step's output
// and diverges over the next few.
fn kda_layer_in_pool(name: &str, threads: usize) -> (Vec<f32>, Vec<f32>) {
    let v = load(name);
    let d = k3::ops::KdaDims {
        hidden: shape(&v, "in")[2],
        heads: i(&v, "H"),
        head_dim: i(&v, "d_k"),
        conv_k: i(&v, "conv_k"),
        gate_lb: f(&v, "lower_bound"),
        rms_eps: f(&v, "rms_eps"),
    };
    let t: Vec<Vec<f32>> = [
        "q_proj", "k_proj", "v_proj", "g_proj", "o_proj", "f_a", "f_b", "b_proj", "q_conv",
        "k_conv", "v_conv", "A_log", "dt_bias", "o_norm",
    ]
    .iter()
    .map(|k| ten(&v, k))
    .collect();
    let w = k3::ops::KdaW {
        q: k3::ops::W::F32(&t[0]),
        k: k3::ops::W::F32(&t[1]),
        v: k3::ops::W::F32(&t[2]),
        g: k3::ops::W::F32(&t[3]),
        o: k3::ops::W::F32(&t[4]),
        f_a: k3::ops::W::F32(&t[5]),
        f_b: k3::ops::W::F32(&t[6]),
        b: k3::ops::W::F32(&t[7]),
        q_conv: &t[8],
        k_conv: &t[9],
        v_conv: &t[10],
        a_log: &t[11],
        dt_bias: &t[12],
        o_norm: &t[13],
    };
    let x = ten(&v, "in");
    let t_len = x.len() / d.hidden;
    rayon::ThreadPoolBuilder::new()
        .num_threads(threads)
        .build()
        .unwrap()
        .install(|| {
            let mut state = vec![0f32; k3::ops::kda_state_len(&d)];
            let mut got = vec![0f32; t_len * d.hidden];
            k3::ops::kda_layer(&mut got, &x, &w, &d, t_len, &mut state);
            (got, state)
        })
}

fn kda_thread_independence(name: &str) {
    let (out1, st1) = kda_layer_in_pool(name, 1);
    let (out8, st8) = kda_layer_in_pool(name, 8);
    for (i, (&a, &b)) in out1.iter().zip(&out8).enumerate() {
        assert_eq!(a.to_bits(), b.to_bits(), "{name}: out[{i}] moved with the thread count");
    }
    for (i, (&a, &b)) in st1.iter().zip(&st8).enumerate() {
        assert_eq!(a.to_bits(), b.to_bits(), "{name}: state[{i}] moved with the thread count");
    }
}

#[test]
fn kda_layer_single_token_is_independent_of_thread_count() {
    kda_thread_independence("kda_layer1");
}

// Eight tokens is the case that matters: with one token every head's recurrence is a
// single step and a state-sharing bug has nowhere to show.
#[test]
fn kda_layer_eight_tokens_is_independent_of_thread_count() {
    kda_thread_independence("kda_layer8");
}
